"""
JARVIS Intent Router

Routes recognized intents to the appropriate skill
or AI engine.

M1.5:
AI intent is now connected to the local Ollama brain.
"""

import logging

from skills import system, files, web
from core.ai_brain import ask_ai


logger = logging.getLogger(__name__)


def route(data: dict):
    """
    Route a classified JARVIS command.

    Args:
        data:
            Intent dictionary generated by core.brain.

    Returns:
        Result from the selected handler.
    """

    if not isinstance(data, dict):

        logger.error(
            "Invalid intent data: %r",
            data,
        )

        return False

    intent = data.get(
        "intent"
    )

    # --------------------------------------------------------------
    # SYSTEM
    # --------------------------------------------------------------

    if intent == "system":

        logger.info(
            "Routing system intent: %s",
            data,
        )

        return system.handle(
            data
        )

    # --------------------------------------------------------------
    # FILES
    # --------------------------------------------------------------

    elif intent == "files":

        logger.info(
            "Routing files intent: %s",
            data,
        )

        return files.handle(
            data
        )

    # --------------------------------------------------------------
    # WEB
    # --------------------------------------------------------------

    elif intent == "web":

        logger.info(
            "Routing web intent: %s",
            data,
        )

        return web.handle(
            data
        )

    # --------------------------------------------------------------
    # AI
    # --------------------------------------------------------------

    elif intent == "ai":

        prompt = data.get(
            "target",
            "",
        )

        if not prompt:

            logger.warning(
                "AI intent received without prompt"
            )

            return False

        logger.info(
            "Routing request to AI brain"
        )

        response = ask_ai(
            prompt,
            speak_response=True,
        )

        return response is not None

    # --------------------------------------------------------------
    # UNKNOWN
    # --------------------------------------------------------------

    else:

        logger.warning(
            "Unknown intent: %s",
            data,
        )

        print(
            "❌ Unknown intent:",
            data,
        )

        return False